### ISSUE TITLE
Code Comprehensive Review

### ISSUE THREAD

**Issue by HajimeKawahara** [HajimeKawahara/exojax#427]
Based on the reflections from Bug #414 , we will thoroughly inspect the calculations and implementations of the code up to now. 

## emission spectrum comparison with PetitRadtrans, which was performed when version 1 released, but now many changes since then
- [x] emission w/ pure absorption #457   See the threads below.

## physical settings
- [x] pressure layer  `tests/unittests/atm/layer_test.py` #533
- [x] scale height #533
- [x] [layer optical depth](https://github.com/HajimeKawahara/exojax/blob/master/src/exojax/spec/layeropacity.py) 
```
opfac * xsmatrix * dParr[:, None] * mixing_ratio[:, None] / (mass * gravity)
```
`opfac` is equivalent to  `1.e3/m_u`, where `m_u = scipy.constants.m_u` ([atomic mass in kg](https://docs.scipy.org/doc/scipy/reference/constants.html)). 1.e3 converts to cgs unit.
        
`mixing_ratio`: volume mixing ratio (VMR) or mass mixing ratio (MMR) [N_layer]
`mass`: mean molecular weight for VMR or molecular mass for MMR

Note: when using MMR as molecular abundance parameters, the spectrum does not depend on the mean molecular weight, and therefore scalable by g, i.e. MMR/g.  

## constants
- [x] constants.py 

## metallicity

- [x] zsol.py #535 (bug)

## continuum
- [x] CIA #433

**Comment by ykawashima** [comment]
I performed the comparison of the spectra calculated with the pure absorption case with petitRADTRANS.
The scripts for these plots are included in ``tests/integration/comparison/twostream``.

![wide_R7000](https://github.com/HajimeKawahara/exojax/assets/44265645/436b7d51-a8d8-4a93-b84c-020c4e565f7c)
![narrow_R70000](https://github.com/HajimeKawahara/exojax/assets/44265645/c53c0987-d8e6-4f67-8a5c-430b0baae9af)
![CIA_R70000](https://github.com/HajimeKawahara/exojax/assets/44265645/caa44c9b-ed2e-4051-abc8-34fe22b8d870)

**Comment by HajimeKawahara** [comment]
Thanks! #457

**Comment by ykawashima** [comment]
The plot shows the comparison with petitRADTRANS, including intensity-based calculation like petitRADTRANS. The script for the plot will be included in ``tests/integration/comparison/twostream``. Exojax calculation was performed with the develop branch on Jan. 13th (a5409ae61f50317b2cb9eeb55cbb23dba8d6f2e5).

![narrow_R70000_rtsolver](https://github.com/HajimeKawahara/exojax/assets/44265645/fef656a2-0b00-4cad-bf20-d2c3696f24e4)

**Comment by ykawashima** [comment]
Just updating the figures calculated with petitRADTRANS3.
![wide_R7000](https://github.com/user-attachments/assets/96de6b4f-fcb3-4072-b9c3-d747ecc4e472)
![narrow_R70000](https://github.com/user-attachments/assets/c326cbc6-2999-459e-9444-1c0a3335d556)
![CIA_R70000](https://github.com/user-attachments/assets/aef72659-a868-4ea0-8768-066306a7e626)
